[package]
name = "math"
version = "0.1.1"
authors = ["Alexandre Frigon <alexandre.frigon.1@gmail.com>"]
edition = "2018"


[dependencies]
noise = "0.6.0"
rand_core = "0.5.1"
rand_pcg = "0.2.1"
serde = { version = "1.0", features = ["derive"] }


[lib]
name = "math"
